### PR TITLE
docs(readme): Remove duplicated instruction

### PR DESCRIPTION
**Pull request by XibalbaM**

### CODE REVIEW

**Comment by anhgelus** [comment]
This is not a duplicated instruction because you have to run it once to generate the config file and then you have to rerun it to start the bot, like Bukkit with the eula.txt.

**Comment by XibalbaM** [comment]
Oh ok my bad

**Comment by anhgelus** [comment]
I'll edit the README to add this information.

**Comment by anhgelus** [comment]
fe021be15be8f380bcfe5934c51f1943cf2b6f63

**Pull request closed without merging**
